# Rule Providers for this version (versioned_rules/2025-09-23-1)
# Generated at: 2025-09-23 02:52:32 UTC
rule-providers:
  # åŸå§‹åç§°: ğŸ‘¨â€ğŸ’» GitHub
  GitHub_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/GitHub_domain.mrs"
    path: "./rules/GitHub_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡ (Domain)
  Inside_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Inside_domain.mrs"
    path: "./rules/Inside_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡ (IP)
  Inside_ipcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Inside_ipcidr.mrs"
    path: "./rules/Inside_ipcidr.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡ (Unsupported)
  Inside_other:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Inside_other.list"
    path: "./rules/Inside_other.list"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡
  SteamCN_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/SteamCN_domain.mrs"
    path: "./rules/SteamCN_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸš€ å›½å¤–æµé‡ (Domain)
  Outside_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Outside_domain.mrs"
    path: "./rules/Outside_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸš€ å›½å¤–æµé‡ (IP)
  Outside_ipcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Outside_ipcidr.mrs"
    path: "./rules/Outside_ipcidr.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸš€ å›½å¤–æµé‡ (Unsupported)
  Outside_other:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Outside_other.list"
    path: "./rules/Outside_other.list"
    interval: 86400

  # åŸå§‹åç§°: ğŸ§š AI (Domain)
  ChatGPT_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/ChatGPT_domain.mrs"
    path: "./rules/ChatGPT_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ§š AI (Unsupported)
  ChatGPT_other:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/ChatGPT_other.list"
    path: "./rules/ChatGPT_other.list"
    interval: 86400

  # åŸå§‹åç§°: ğŸ§š AI
  OpenAI_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/OpenAI_domain.mrs"
    path: "./rules/OpenAI_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ§š AI
  Claude_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Claude_domain.mrs"
    path: "./rules/Claude_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ§š AI
  Gemini_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Gemini_domain.mrs"
    path: "./rules/Gemini_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ§š AI
  Copilot_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Copilot_domain.mrs"
    path: "./rules/Copilot_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ§š AI (Domain)
  Perplexity_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Perplexity_domain.mrs"
    path: "./rules/Perplexity_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡
  Lan_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Lan_domain.mrs"
    path: "./rules/Lan_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡ (Domain)
  UnBan_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/UnBan_domain.mrs"
    path: "./rules/UnBan_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸš€ å›½å¤–æµé‡
  PikPak_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/PikPak_domain.mrs"
    path: "./rules/PikPak_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ›¸ IPå½’å±åœ°ä¼ªè£…
  rule-provider_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/rule-provider_domain.mrs"
    path: "./rules/rule-provider_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª (Domain)
  BanAD_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/BanAD_domain.mrs"
    path: "./rules/BanAD_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª (Domain)
  BanProgramAD_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/BanProgramAD_domain.mrs"
    path: "./rules/BanProgramAD_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª (IP)
  BanProgramAD_ipcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/BanProgramAD_ipcidr.mrs"
    path: "./rules/BanProgramAD_ipcidr.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª (Domain)
  BanEasyList_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/BanEasyList_domain.mrs"
    path: "./rules/BanEasyList_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª (IP)
  BanEasyList_ipcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/BanEasyList_ipcidr.mrs"
    path: "./rules/BanEasyList_ipcidr.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª (Domain)
  BanEasyListChina_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/BanEasyListChina_domain.mrs"
    path: "./rules/BanEasyListChina_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª (IP)
  BanEasyListChina_ipcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/BanEasyListChina_ipcidr.mrs"
    path: "./rules/BanEasyListChina_ipcidr.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª (Domain)
  BanEasyPrivacy_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/BanEasyPrivacy_domain.mrs"
    path: "./rules/BanEasyPrivacy_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª (IP)
  BanEasyPrivacy_ipcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/BanEasyPrivacy_ipcidr.mrs"
    path: "./rules/BanEasyPrivacy_ipcidr.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  ZhihuAds_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/ZhihuAds_domain.mrs"
    path: "./rules/ZhihuAds_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ“¹ YouTube
  YouTube_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/YouTube_domain.mrs"
    path: "./rules/YouTube_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¥ Netflix
  Netflix_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Netflix_domain.mrs"
    path: "./rules/Netflix_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¹ DisneyPlus
  Disney_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Disney_domain.mrs"
    path: "./rules/Disney_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ“½ï¸ PrimeVideo
  AmazonPrimeVideo_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/AmazonPrimeVideo_domain.mrs"
    path: "./rules/AmazonPrimeVideo_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¦ HBO
  HBO_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/HBO_domain.mrs"
    path: "./rules/HBO_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¦ HBO
  HBOAsia_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/HBOAsia_domain.mrs"
    path: "./rules/HBOAsia_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¦ HBO
  HBOUSA_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/HBOUSA_domain.mrs"
    path: "./rules/HBOUSA_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ AppleTV
  AppleTV_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/AppleTV_domain.mrs"
    path: "./rules/AppleTV_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¬ EMBY
  Emby_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Emby_domain.mrs"
    path: "./rules/Emby_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¬ EMBY
  Emby_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Emby_domain.mrs"
    path: "./rules/Emby_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ“º å·´å“ˆå§†ç‰¹
  Bahamut_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Bahamut_domain.mrs"
    path: "./rules/Bahamut_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ“º Bilibili (Domain)
  BilibiliHMT_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/BilibiliHMT_domain.mrs"
    path: "./rules/BilibiliHMT_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ“º Bilibili (IP)
  BilibiliHMT_ipcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/BilibiliHMT_ipcidr.mrs"
    path: "./rules/BilibiliHMT_ipcidr.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ“º Bilibili (Domain)
  Bilibili_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Bilibili_domain.mrs"
    path: "./rules/Bilibili_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ“º Bilibili (Unsupported)
  Bilibili_other:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Bilibili_other.list"
    path: "./rules/Bilibili_other.list"
    interval: 86400

  # åŸå§‹åç§°: ğŸµ Spotify
  Spotify_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Spotify_domain.mrs"
    path: "./rules/Spotify_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¶ TikTok
  TikTok_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/TikTok_domain.mrs"
    path: "./rules/TikTok_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸŒ å›½å¤–åª’ä½“
  GlobalMedia_Classical_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/GlobalMedia_Classical_domain.mrs"
    path: "./rules/GlobalMedia_Classical_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸŒ å›½å†…åª’ä½“
  ChinaMedia_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/ChinaMedia_domain.mrs"
    path: "./rules/ChinaMedia_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ“¢ è°·æ­ŒFCM (Domain)
  GoogleFCM_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/GoogleFCM_domain.mrs"
    path: "./rules/GoogleFCM_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ“¢ è°·æ­ŒFCM (IP)
  GoogleFCM_ipcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/GoogleFCM_ipcidr.mrs"
    path: "./rules/GoogleFCM_ipcidr.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡ (Domain)
  GoogleCN_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/GoogleCN_domain.mrs"
    path: "./rules/GoogleCN_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: â“‚ï¸ å¾®è½¯äº‘ç›˜
  OneDrive_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/OneDrive_domain.mrs"
    path: "./rules/OneDrive_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: â“‚ï¸ å¾®è½¯æœåŠ¡
  Microsoft_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Microsoft_domain.mrs"
    path: "./rules/Microsoft_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ è‹¹æœæœåŠ¡
  Apple_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Apple_domain.mrs"
    path: "./rules/Apple_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ“² Telegram
  Telegram_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Telegram_domain.mrs"
    path: "./rules/Telegram_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¤– Discord
  Discord_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Discord_domain.mrs"
    path: "./rules/Discord_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ® æ¸¸æˆå¹³å°
  Game_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Game_domain.mrs"
    path: "./rules/Game_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸš€ å›½å¤–æµé‡ (Domain)
  ProxyGFWlist_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/ProxyGFWlist_domain.mrs"
    path: "./rules/ProxyGFWlist_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸš€ å›½å¤–æµé‡ (IP)
  ProxyGFWlist_ipcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/ProxyGFWlist_ipcidr.mrs"
    path: "./rules/ProxyGFWlist_ipcidr.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸš€ å›½å¤–æµé‡ (Unsupported)
  ProxyGFWlist_other:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/ProxyGFWlist_other.list"
    path: "./rules/ProxyGFWlist_other.list"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡ (Domain)
  ChinaDomain_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/ChinaDomain_domain.mrs"
    path: "./rules/ChinaDomain_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡ (IP)
  ChinaDomain_ipcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/ChinaDomain_ipcidr.mrs"
    path: "./rules/ChinaDomain_ipcidr.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡ (Unsupported)
  ChinaDomain_other:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/ChinaDomain_other.list"
    path: "./rules/ChinaDomain_other.list"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡ (IP)
  ChinaCompanyIp_ipcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/ChinaCompanyIp_ipcidr.mrs"
    path: "./rules/ChinaCompanyIp_ipcidr.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡ (Domain)
  Download_domain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Download_domain.mrs"
    path: "./rules/Download_domain.mrs"
    interval: 86400

  # åŸå§‹åç§°: ğŸ¯ å›½å†…æµé‡ (Unsupported)
  Download_other:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/qingwo1992/mihomo-mrs/main/versioned_rules/2025-09-23-1/rules/Download_other.list"
    path: "./rules/Download_other.list"
    interval: 86400

